### ISSUE TITLE
Missing plugin.yml file

### ISSUE THREAD

**Issue by kummm** [JCulley/ProQuests-Documentaion#26]
[20:52:33 ERROR]: Could not load 'plugins\ProQuests-2.0.3.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[PaperSpigot-1.12.2-b1262.jar:git-Paper-1262]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) [PaperSpigot-1.12.2-b1262.jar:git-Paper-1262]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:307) [PaperSpigot-1.12.2-b1262.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [PaperSpigot-1.12.2-b1262.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.12.2-b1262.jar:git-Paper-1262]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml

**Comment by JCulley** [comment]
Your issue will be ignored next time if you do not follow the guidelines. https://www.spigotmc.org/resources/proquests-1-7-1-12-2-25-off-v2-sale-give-players-objectives.18249/update?update=199660
